name: Conditional Workflow Example

on:
  workflow_dispatch:
    inputs:
      matrix_values:
        description: 'Comma-separated string values'
        required: true
        default: 'value1,value2,value3'

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix_values: ${{ steps.set-matrix.outputs.matrix_values }}
    steps:
      - name: Set up matrix values
        id: set-matrix
        run: |
          # Get the matrix_values input (a comma-separated string)
          matrix_values="${{ github.event.inputs.matrix_values }}"
          
          # Convert the input string into a JSON array format
          matrix_values_json="[\"$(echo $matrix_values | tr ',' '","')\"]"
          
          # Output the JSON array
          echo "Matrix values: $matrix_values_json"
          
          # Set matrix_values as output for other jobs to use
          echo "::set-output name=matrix_values::$matrix_values_json"

  conditional-jobs:
    needs: setup-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{ fromJson(needs.setup-matrix.outputs.matrix_values) }}
      fail-fast: false
    steps:
      - name: Print matrix value
        run: |
          echo "Current matrix value: ${{ matrix.value }}"
