name: Test Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        if: github.event_name == 'push' && 1==1
        uses: actions/setup-node@v2
        with:
          node-version: '16'
  Release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        if: github.event_name == 'push' && 1==1
        uses: actions/setup-node@v2
        with:
          node-version: '16'

  call-reusable-workflow:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      node-env: production
      api-url: https://api.example.com
