name: Workflow with Matrix

on:
  workflow_run:
    workflows: ["Conditional Workflow"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Parse array
        id: parse-array
        run: echo ${{ github.event.workflow_run.outputs.array }} | tr ',' '\n' | jq -R -s -c 'split("\n")[:-1]'
        shell: bash
        env:
          ARRAY: ${{ github.event.workflow_run.outputs.array }}

      - name: Set matrix variable
        id: set-matrix
        run: echo "::set-output name=matrix::${{ steps.parse-array.outputs.result }}"

  matrix-build:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        string_values: ${{ fromJson(needs.build.outputs.matrix) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print matrix values
        if: ${{ matrix.string_values != 'skip' }}
        run: echo "Processing ${{ matrix.string_values }}"
